# Generated by Django 5.0.3 on 2024-04-18 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Заголовок')),
                ('slug', models.CharField(max_length=100, verbose_name='Ссылка')),
                ('text', models.TextField(verbose_name='Содержимое')),
                ('image', models.ImageField(blank=True, null=True, upload_to='blog/', verbose_name='Превью')),
                ('creation_date', models.DateField(auto_now_add=True)),
                ('published', models.BooleanField(verbose_name='Опубликовано')),
                ('view_count', models.IntegerField(default=0, verbose_name='Кол-во просмотров')),
            ],
            options={
                'verbose_name': 'Запись',
                'verbose_name_plural': 'Записи',
                'ordering': ('id', 'title'),
            },
        ),
    ]
